name: Backport Workflows
on:
  pull_request:
    branches:
      - test-main
      - test-stable
    types: [closed]

env:
  AWS_REGION: eu-west-1
  UV_VERSION: "0.6.10"
  PYTHON_VERSION: "3.11.11"
  REPOSITORY_NAME: "pypi-all"

jobs:
  backport-stable-pr:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'test-main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the base branch (test-main)
        uses: actions/checkout@v4.1.1
        with:
          ref: test-main
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Fetch all branches from origin
        run: git fetch origin

      - name: Checkout the target branch (test-stable)
        run: git checkout test-stable

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
      
      - name: Merge changes from test-main into test-stable with unrelated histories
        run: |
          git merge origin/test-main --no-edit --allow-unrelated-histories --strategy-option=theirs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Update version for stable (test-stable)
        id: update-version-stable
        run: |
          VERSION=$(sed -nE 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' pyproject.toml)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-3)
          NEW_VERSION="${MAJOR_MINOR}.${{ steps.date.outputs.date }}"  # Ensure the version is updated properly.
          sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          cat pyproject.toml

      # Create the pull request with a valid branch name by sanitizing the version
      - name: Create main-to-stable PR
        id: test-stable-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: 'Auto-update version for stable'
          branch: 'backport-${{ steps.update-version-stable.outputs.new_version }}-${{ steps.date.outputs.date }}'
          title: '[AUTO] Backport main -> stable'
          branch-suffix: timestamp
          base: test-stable
          body: |
            Update version in pyproject.toml to ${{ steps.update-version-stable.outputs.new_version }}.
            This PR is automatically generated.

      - name: Check created test-stable PR number
        run: |
          echo "Pull Request Number - ${{ steps.test-stable-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.test-stable-pr.outputs.pull-request-url }}"

      - name: Merge stable PR
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.BOT_ACCESS_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt('${{ steps.test-stable-pr.outputs.pull-request-number }}'),
              merge_method: 'merge',
            });
  backport-dev-pr:
    needs: backport-stable-pr  # Ensure backport-dev-pr runs after backport-stable-pr succeeds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the base branch (test-stable)
        uses: actions/checkout@v4.1.1
        with:
          ref: test-stable

      - name: Fetch all branches from origin
        run: git fetch origin

      - name: Checkout the target branch (test-develop)
        run: git checkout test-develop

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Merge changes from test-stable into test-develop with unrelated histories
        run: |
          git merge origin/test-stable --no-edit --allow-unrelated-histories --strategy-option=theirs

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Update version for develop (test-develop)
        id: version
        run: |
          VERSION=$(grep -E '^version = *"' pyproject.toml | head -n1 | sed -E 's/version *= *"(.)"/\1/')
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-3)
          DATE=$(date +'%Y%m%d')
          NEW_VERSION="${MAJOR_MINOR}.${DATE}-dev"

          # Sanitize branch name: Remove invalid characters like `=`, `"`, and spaces
          SANITIZED_BRANCH_NAME="backport-${NEW_VERSION//[[:space:]]/}"  # Remove spaces
          SANITIZED_BRANCH_NAME="${SANITIZED_BRANCH_NAME//\"/}"  # Remove quotes
          SANITIZED_BRANCH_NAME="${SANITIZED_BRANCH_NAME//=/-}"  # Replace equals sign with a hyphen

          sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          echo "sanitized_branch_name=$SANITIZED_BRANCH_NAME" >> $GITHUB_OUTPUT
          cat pyproject.toml
      - name: Commit and push updated version to pyproject.toml
        run: |
          git add pyproject.toml
          git commit -m "Auto-update version to ${{ steps.version.outputs.new_version }}"
          git push origin test-develo
      - name: Create stable-to-develop PR
        id: test-develop-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: 'Auto-update version for develop'
          branch: ${{ steps.version.outputs.sanitized_branch_name }}
          title: '[AUTO] Backport stable -> develop'
          branch-suffix: timestamp
          base: test-develop
          body: |
            Updated version in pyproject.toml to: ${{ steps.version.outputs.new_version }}.
            This PR is automatically generated.

      # Uncomment below if you want to automatically merge the PR for develop
      - name: Merge develop PR
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.BOT_ACCESS_TOKEN }}
          script: |
            const pull_number = parseInt('${{ steps.test-develop-pr.outputs.pull-request-number }}');
            if (!pull_number) {
              core.setFailed('PR number not found');
            }
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: pull_number,
              merge_method: 'merge',
            });
