name: Backport Workflows
on:
  pull_request:
    branches:
      - test-main
      - test-stable
    types: [closed]

env:
  AWS_REGION: eu-west-1
  UV_VERSION: "0.6.10"
  PYTHON_VERSION: "3.11.11"
  REPOSITORY_NAME: "pypi-all"

jobs:
  backport-stable-pr:
    if: ${{ github.event.pull_request.merged && github.event.pull_request.base.ref == 'test-main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: test-main

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Update version for stable
        id: update-version-stable
        run: |
          VERSION=$(sed -nE 's/^[[:space:]]*version[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/p' pyproject.toml)
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          echo "version : $VERSION"
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-3)
          echo "major minor : $MAJOR_MINOR"
          NEW_VERSION="${MAJOR_MINOR}.${{ steps.date.outputs.date }}"
          echo "new version : $NEW_VERSION"
          sed -i "s/version = \"$VERSION\"/version = \"$NEW_VERSION\"/" pyproject.toml
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
          cat pyproject.toml

      - name: Print version for stable
        run: echo "Updated version for stable:${{steps.update-version-stable.outputs.version }}"

      - name: Create main-to-stable PR
        id: test-stable-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: 'Auto-update version for stable'
          branch: 'backport-${{ steps.update-version-stable.outputs.version }}-${{ steps.date.outputs.date }}'
          title: '[AUTO] Backport main -> stable'
          branch-suffix: timestamp
          base: test-stable
          body: |
            Update version in pyproject.toml to ${{ steps.update-version-stable.outputs.version }}.
            This PR is automatically generated.

      - name: Check created test-stable PR number
        run: |
          echo "Pull Request Number - ${{ steps.test-stable-pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.test-stable-pr.outputs.pull-request-url }}"

      - name: Merge stable PR
        uses: actions/github-script@v6.1.0
        with:
          github-token: ${{ secrets.BOT_ACCESS_TOKEN }}
          script: |
            await github.rest.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: parseInt('${{ steps.test-stable-pr.outputs.pull-request-number }}'),
              merge_method: 'merge',
            });

  backport-dev-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
        with:
          ref: test-stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Update version for develop
        id: version
        run: |
          VERSION=$(grep -E '^version = *"' pyproject.toml | head -n1 | sed -E 's/version *= *"(.)"/\1/')
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
          MAJOR_MINOR=$(echo $VERSION | cut -d. -f1-3)
          DATE=$(date +'%Y%m%d')
          NEW_VERSION="${MAJOR_MINOR}.${DATE}-dev"
          sed -i "s/version = \"${VERSION}\"/version = \"${NEW_VERSION}\"/" pyproject.toml
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Print version for develop
        run: echo "Updated version for develop:${{steps.version.outputs.version }}"

      - name: Create stable-to-develop PR
        id: test-develop-pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.BOT_ACCESS_TOKEN }}
          commit-message: 'Auto-update version for develop'
          branch: 'backport-${{ steps.version.outputs.version }}'
          title: '[AUTO] Backport stable -> develop'
          branch-suffix: timestamp
          base: test-develop
          body: |
            Updated version in pyproject.toml to: ${{ steps.version.outputs.version }}.
            This PR is automatically generated.

      # Uncomment the steps below if you want to automatically merge the PR for the develop branch
      # - name: Merge develop PR
      #   uses: actions/github-script@v6.1.0
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     script: |
      #       await github.rest.pulls.merge({
      #         owner: context.repo.owner,
      #         repo: context.repo.repo,
      #         pull_number: parseInt('${{ steps.test-develop-pr.outputs.pull-request-number }}'),
      #         merge_method: 'merge',
      #       });
